### PR TITLE
Fix restrict-full-import

### LINKED ISSUE #222: restrict-full-import fails on "empty" array pattern
Failing code:

```js
const [, foo] = bar;
```

we try to access `type`, but the empty slot is actually just `null`:

screen shot 2019-02-15 at 11 53 56 am

### PR DESCRIPTION
**Pull request by cartogram**
Closes https://github.com/Shopify/eslint-plugin-shopify/issues/222

### CODE REVIEW

File: lib/rules/restrict-full-import.js [hunk 1]
```diff
@@ -41,6 +41,9 @@ module.exports = {
           })) ||
         (left.type === 'ArrayPattern' &&
           left.elements.some((element) => {
+            if (element === null) {
+              return false;
+            }
             return element.type === 'RestElement';
```
Comment (lemonmade) [inline lib/rules/restrict-full-import.js]: I’d probably just do element != null && here

**Review by lemonmade — APPROVED** [review]
