### PR TITLE
Fixes `shopify/jest/no-if` to now ignore if statements inside block statements 

### LINKED ISSUE #263: jest/no-if should not complain when not directly nested in `it`
The following code currently warns, but shouldn't:

```ts
it('works', () => {
  const values = something.map((thing) => {
    if (thing.isFoo) {
      return thing.foo
    } else {
      return thing.bar;
    }
  });

  expect(values).toStrictEqual(['foo']);
});
```

### PR DESCRIPTION
**Pull request by cartogram**
Closes https://github.com/Shopify/eslint-plugin-shopify/issues/263

### CODE REVIEW

File: lib/rules/jest/no-if.js [hunk 1]
```diff
@@ -94,3 +106,10 @@ function hasEmptyBody(node) {
     node.arguments[1].body.body.length === 0
   );
 }
+
+function skip(state) {
+  return (
+    state.callExpressionDepth === 0 ||
+    state.blockStatementDepth > state.callExpressionDepth
```
Comment (lemonmade) [inline lib/rules/jest/no-if.js]: I have a little trouble understanding this condition, can you explain it?

**Review by lemonmade — COMMENTED** [review]
lol my other review looks really dumb now

File: lib/rules/jest/no-if.js (hunk 1 above)
Comment (cartogram) [reply lib/rules/jest/no-if.js]: So the first part is the same as what was there previously if we are not inside of a testing-CallExpression (`it()`, `test()`, etc...), then we don't care about if statements. 

The part after the `||` is new and is trying to determine if we are inside of a BlockStatement that is inside of (but not attached to) a testing-CallExpesssion. Because the opening `{...}` to the CallExpesssion, for example in `it('works'){ //here... }`, will increase both our blockStatementDepth and callExpessionDepth by one, the greater-than check will tell us if we have entered a BlockStatement that is NOT attached to a CallExpression. In other words, if the blockStatementDepth is greater than the callStatementDepth, than we have entered at least one more BlockStatment, while also inside of a testing-CallExpession, which is valid and we want to `skip` (not report) the current ifStatement.

Open to other ways to handle this as well!

Comment (lemonmade) [reply lib/rules/jest/no-if.js]: Does it catch things like defining an in-line function in an it block (const foo = () => bar ? baz : qux)?

Comment (cartogram) [reply lib/rules/jest/no-if.js]: I think that should be covered already, will add a test and confirm 👍

Comment (cartogram) [reply lib/rules/jest/no-if.js]: @lemonmade added passing tests for the arrow functions as well.

File: lib/rules/jest/no-if.js [hunk 2]
```diff
@@ -25,63 +25,60 @@ module.exports = {
         'This is usually an indication that you',
         'are attempting to test too much at once',
         'or not testing what you intend to.',
-        'Consider breaking the conditional statement out',
-        'into a separate test to resolve this error.',
+        'Consider writing a separate test for',
+        'each fork in the conditional statement.',
```
Comment (lemonmade) [inline lib/rules/jest/no-if.js:30]: The other case I often see this: people have a possibly null value and bail out to not make TypeScript mad. We should call that one out, and push them to use `!` instead

File: lib/rules/jest/no-if.js [hunk 3]
```diff
@@ -25,63 +25,60 @@ module.exports = {
...
-          return;
-        }
-        callExpressionDepth++;
-      },
-      IfStatement(node) {
-        if (callExpressionDepth === 0) {
-          return;
-        }
+    const changeNestedDepth = (increase) => () =>
+      inTest(state) && (increase ? state.nestedDepth++ : state.nestedDepth--);
```
Comment (lemonmade) [inline lib/rules/jest/no-if.js]: This is too clever by a lot IMO, add some blocks and conditions instead

File: lib/rules/jest/no-if.js [hunk 4]
```diff
@@ -25,63 +25,60 @@ module.exports = {
...
+
+    return {
+      CallExpression: changeDepth(true),
+      FunctionExpression: changeNestedDepth(true),
+      ArrowFunctionExpression: changeNestedDepth(true),
+      IfStatement: ifStatement('noIf'),
+      ConditionalExpression: ifStatement('noConditional'),
+      'FunctionExpression:exit': changeNestedDepth(),
+      'ArrowFunctionExpression:exit': changeNestedDepth(),
+      'CallExpression:exit': changeDepth(),
```
Comment (lemonmade) [inline lib/rules/jest/no-if.js]: Not sure if me or the pattern, but I had to read through this a lot to understand what the `changeNestedDepth`/ `changeDepth`/ with/ without argument actually meant.

Comment (lemonmade) [reply lib/rules/jest/no-if.js]: Personally, I'd probably just keep a stack of call expressions (as an array), every time you enter push `true` or `false` for if it's a test or not, every time you exit pop. Then, checking for an invalid conditional is just checking if the current stack entry is `true` or `false`.

**Review by lemonmade — CHANGES_REQUESTED** [review]

**Comment by cartogram** [comment]
@lemonmade ready for another look

File: lib/rules/jest/no-if.js [hunk 5]
```diff
@@ -17,69 +17,54 @@ module.exports = {
...
         'This is usually an indication that you',
         'are attempting to test too much at once',
         'or not testing what you intend to.',
-        'Consider breaking the conditional statement out',
-        'into a separate test to resolve this error.',
+        'Consider writing a separate test for',
+        'each fork in the conditional statement.',
+        'If your conditionals are required to',
+        'satisfy the typescript type checker, consider',
+        'using a non-null assertion operator (!) instead.',
```
Comment (lemonmade) [inline lib/rules/jest/no-if.js:33]: ❤️

File: lib/rules/jest/no-if.js [hunk 6]
```diff
@@ -17,69 +17,54 @@ module.exports = {
...
-      },
-      ConditionalExpression(node) {
-        if (callExpressionDepth === 0) {
-          return;
-        }
+      if (!lastCallExpression) {
+        return;
+      }
+
+      if (isTestDefinition(lastCallExpression)) {
```
Comment (lemonmade) [inline lib/rules/jest/no-if.js]: Is there a reason to compute this manually every time? Can the stack just have the results of calling this?

**Review by lemonmade — APPROVED** [review]
